name: Deployment to Dev environment

on:
  workflow_dispatch:
  push:
    branches: ['dev']
jobs:
  build:
    name: Build and Deploy to ECS
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Inject commit details
        run: git show --summary > last-commit.txt

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.GH_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.GH_AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-3

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v2

      - name: BACKEND Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: 938978445243.dkr.ecr.eu-west-3.amazonaws.com/monetiseur-nonprod:frontend-dev-latest        

      - name: Force ECS Backend Services restart
        run: |
          aws ecs update-service --cluster tf--ecs-nonprod --service service-dev-backend --force-new-deployment
